[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# sdm_adding_card context
# regex also has Talisman compat
[[patches]]
[patches.regex]
target = "card.lua"
pattern = '''
[\t ]*function Card:add_to_deck[\s\S]*?
(?<indent>[\t ]*)if G\.GAME\.blind.*then G\.E_MANAGER:add_event\(Event\(\{ func = function\(\) G\.GAME\.blind:set_blind\(nil, true, nil\); return true end \}\)\) end\n'''
position = "after"
payload = """
if not from_debuff and G.jokers and #G.jokers.cards > 0 then
    for i = 1, #G.jokers.cards do
        G.jokers.cards[i]:calculate_joker({sdm_adding_card = true, card = self})
    end
end

"""
line_prepend = '$indent'

# No shop planets
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "elseif v.id == 'no_shop_jokers' then"
position = "before"
payload = """
elseif v.id == 'no_shop_planets' then
    self.GAME.planet_rate = 0
"""
match_indent = true

# Warehouse negative effect
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "function Card:can_sell_card(context)"
position = "after"
payload = """
    if (SMODS and SMODS.find_card("j_sdm_warehouse", false)) then
        return self.ability.name ~= "Warehouse"
    end
"""
match_indent = true

# Modded Deck/Sleeve effect
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if v.no_pool_flag and G.GAME.pool_flags[v.no_pool_flag] then add = nil end"
position = "before"
payload = '''
-- TODO: Make Cryptid's DoE deck not spawn vanilla stuff
local curr_deck = (G.GAME.viewed_back and G.GAME.viewed_back.name) or (G.GAME.selected_back and G.GAME.selected_back.name) or "Red Deck"
local curr_sleeve = (CardSleeves and G.GAME.selected_sleeve) or "sleeve_casl_none"
if ((curr_deck == "b_sdm_modded" or curr_deck == "b_sdm_deck_of_stuff") or curr_sleeve == "sleeve_sdm_modded") and not v.mod and v.set == "Joker" then add = nil end
if ((curr_deck == "b_sdm_modded" or curr_deck == "b_sdm_deck_of_stuff") and curr_sleeve == "sleeve_sdm_modded") and not v.mod then add = nil end
'''
match_indent = true