[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# sdm_adding_card context
# regex also has Talisman compat
[[patches]]
[patches.regex]
target = "card.lua"
pattern = '''
[\t ]*function Card:add_to_deck[\s\S]*?
(?<indent>[\t ]*)if G\.GAME\.blind.*then G\.E_MANAGER:add_event\(Event\(\{ func = function\(\) G\.GAME\.blind:set_blind\(nil, true, nil\); return true end \}\)\) end\n'''
position = "after"
payload = """
if not from_debuff and G.jokers and #G.jokers.cards > 0 then
    for i = 1, #G.jokers.cards do
        G.jokers.cards[i]:calculate_joker({sdm_adding_card = true, card = self})
    end
end

"""
line_prepend = '$indent'

# No shop planets
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "elseif v.id == 'no_shop_jokers' then"
position = "before"
payload = """
elseif v.id == 'no_shop_planets' then
    self.GAME.planet_rate = 0
"""
match_indent = true

# Warehouse negative effect
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "function Card:can_sell_card(context)"
position = "after"
payload = """
    if (SMODS and next(SMODS.find_card("j_sdm_warehouse"))) and self.ability.name ~= "Warehouse" then
        return false
    end
"""
match_indent = true

# Modded Deck/Sleeve effect
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if v.no_pool_flag and G.GAME.pool_flags[v.no_pool_flag] then add = nil end"
position = "before"
payload = '''
local curr_deck = (G.GAME.viewed_back and G.GAME.viewed_back.name) or (G.GAME.selected_back and G.GAME.selected_back.name) or "Red Deck"
local curr_sleeve = (CardSleeves and G.GAME.selected_sleeve) or "sleeve_casl_none"
if ((curr_deck == "b_sdm_modders" or curr_deck == "b_sdm_deck_of_stuff") or curr_sleeve == "sleeve_sdm_modders") and (not v.original_key or (v.class_prefix..'_'..v.original_key == v.key)) and v.set == "Joker" then add = nil end
if ((curr_deck == "b_sdm_modders" or curr_deck == "b_sdm_deck_of_stuff") and curr_sleeve == "sleeve_sdm_modders") and (not v.original_key or (v.class_prefix..'_'..v.original_key == v.key)) then add = nil end
'''
match_indent = true

# SDM_0's Deck and Sleeve effect (code from Ceres "Ceres Joker")
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "_pool[#_pool + 1] = v.key"
position = "before"
payload = '''
if curr_deck and (curr_deck == "b_sdm_0_s" or curr_deck == "b_deck_of_stuff") then
    if string.sub(v.key, 1, 6) == "j_sdm_" then
        for i = 1, 4 do
            _pool[#_pool + 1] = v.key
            _pool_size = _pool_size + 1
        end
    end
end
if (curr_sleeve and curr_sleeve == "sleeve_sdm_0_s") then
    if string.sub(v.key, 1, 6) == "j_sdm_" then
        for i = 1, (curr_deck and (curr_deck == "b_sdm_0_s" or curr_deck == "b_deck_of_stuff" and 5)) or 4 do
            _pool[#_pool + 1] = v.key
            _pool_size = _pool_size + 1
        end
    end
end
'''
match_indent = true

# Ouija Board secret poker hand list (code from Ortalab)
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''boot_timer('splash prep', 'end',1)'''
position = "after"
payload = '''
if (SMODS.Mods['sdm0sstuff'] or {}).can_load then
    for k, v in pairs(G.GAME.hands) do
        if v.visible == false then
            G.P_CENTERS['j_sdm_ouija_board'].config.extra.secret_poker_hands[#G.P_CENTERS['j_sdm_ouija_board'].config.extra.secret_poker_hands+1] = k
        end
    end
end
'''
match_indent = true

# "Patch" effect
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:set_debuff(should_debuff)'''
position = "after"
payload = '''
    if G.GAME and G.GAME.patch_disable then return end
'''
match_indent = true

# Prevent "Disabled" message with "Patch"
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''card_eval_status_text(self, 'extra', nil, nil, nil, {message = localize('k_disabled_ex'),colour = G.C.FILTER, delay = 0.45})'''
position = "at"
payload = '''
if G.GAME and not G.GAME.patch_disable then
    card_eval_status_text(self, 'extra', nil, nil, nil, {message = localize('k_disabled_ex'),colour = G.C.FILTER, delay = 0.45})
end
'''
match_indent = true

# Bread eval
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''local nu_chip, nu_mult = G.GAME.selected_back:trigger_effect{context = 'final_scoring_step', chips = hand_chips, mult = mult}'''
position = "before"
payload = '''
-- SDM_0's Stuff bakery consumable evaluation
sendDebugMessage("reached function bakery")
if G.GAME and G.GAME.bakery then
    local bkr_chips, bkr_mult, bkr_xmult = 0, 0, 0
    if G.GAME.bakery and #G.GAME.bakery > 0 then
        for i = #G.GAME.bakery, 1, -1 do
            if G.GAME.bakery[i].type == "chips" then
                bkr_chips = bkr_chips + G.GAME.bakery[i].amount
            elseif G.GAME.bakery[i].type == "mult" then
                bkr_mult = bkr_mult + G.GAME.bakery[i].amount
            elseif G.GAME.bakery[i].type == "xmult" then
                bkr_xmult = bkr_xmult + G.GAME.bakery[i].amount
            end
            G.GAME.bakery[i].triggers = G.GAME.bakery[i].triggers - 1
            if G.GAME.bakery[i].triggers < 1 then
                table.remove(G.GAME.bakery, i)
            end
        end
        bkr_xmult = bkr_xmult or 1
        mult = mod_mult(mult+bkr_mult*bkr_xmult)
        hand_chips = mod_chips(hand_chips+bkr_chips)
        update_hand_text({delay = 0}, {chips = hand_chips, mult = mult})
        -- TODO: Figure out how to better animate bread bonus
    end
end

'''
match_indent = true